services:
  worktimer:
    build: .
    image: worktimer-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./worktimer.db:/app/worktimer.db
    # environment:
    # Add any environment variables here if needed
    # EXAMPLE_VAR: value
    restart: unless-stopped
