services:
  worktimer:
    build: .
    image: worktimer-app:latest
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=${DB_NAME}
      - DEBUG_MODE=${DEBUG_MODE}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
